import polars as pl

SAMPLE_SCHEMA = pl.Schema(
    {
        "trader": pl.String,
        "token_id": pl.String,
        "question": pl.String,
        "event_market_name": pl.String,
        "maker_token_outcome": pl.String,
        "settlement_value": pl.Float64,
        "final_outcome": pl.String,
        "condition_id": pl.String,
        "neg_risk": pl.String,
        "market_start_time": pl.String,
        "market_end_time": pl.String,
        "orders_end_time": pl.String,
        "shares_delta": pl.Float64,
        "shares_bought": pl.Float64,
        "shares_sold": pl.Float64,
        "trade_usd_invested": pl.Float64,
        "trade_usd_realized": pl.Float64,
        "trades": pl.Float64,
        "merge_shares_delta": pl.Float64,
        "merges": pl.Float64,
        "merge_usd_invested": pl.Float64,
        "merge_usd_realized": pl.Float64,
        "split_shares_delta": pl.Float64,
        "splits": pl.Float64,
        "split_usd_invested": pl.Float64,
        "split_usd_realized": pl.Float64,
        "convert_to_yes_shares_delta": pl.Float64,
        "convert_to_yes_s": pl.Float64,
        "convert_from_no_shares_delta": pl.Float64,
        "convert_from_no_s": pl.Float64,
        "convert_from_no_usd_realized": pl.Float64,
        "transfer_in_shares_delta": pl.Float64,
        "transfer_ins": pl.Float64,
        "transfer_out_shares_delta": pl.Float64,
        "transfer_outs": pl.Float64,
        "usd_invested": pl.Float64,
        "usd_realized": pl.Float64,
        "total_shares": pl.Float64,
        "resolution_profit": pl.Float64,
        "final_profit": pl.Float64,
        "h": pl.Float64,
        "pnl_bucket": pl.Float64,
        "rn": pl.Float64,
    }
)

CLOSED_POSITIONS_SCHEMA = pl.Schema(
    {
        "proxyWallet": pl.String,
        "asset": pl.String,
        "conditionId": pl.String,
        "avgPrice": pl.Float64,
        "totalBought": pl.Float64,
        "realizedPnl": pl.Float64,
        "curPrice": pl.Float64,
        "title": pl.String,
        "slug": pl.String,
        "icon": pl.String,
        "eventSlug": pl.String,
        "outcome": pl.String,
        "outcomeIndex": pl.Float64,
        "oppositeOutcome": pl.String,
        "oppositeAsset": pl.String,
        "endDate": pl.String,
        "timestamp": pl.Int128,
    }
)
